# -*- coding: utf-8 -*-
"""DAA-P2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_Sugth22aXjtp23mRFdD8DOZcxLpoKP
"""

import numpy as np

# membuat array
nilai_siswa = np.array([85, 55, 40, 90])

# mengakses data pada array
print(nilai_siswa[3])

print("Hello World!")
print("Nama saya Nurfajrian Abdurrohman")
print("NIM saya 2023071045")

if 5 > 2:
    print("Five is greater than two!")

x = 5
y = "John"
print(x)
print(y)

x = 4
x = "Sally"
print(x)

mylist = [1,2,3,4,5]

getFirst = mylist[0]
getSecond = mylist[1]

print(getFirst)
print(getSecond)

mylist = [1,2,3,4,5]

getFirst = mylist[0]
getLast = mylist[4]

print(getFirst)
print(getLast)

mylist = [1, 2, 3, 4, 5]

getKali = 1
for num in mylist:
    getKali *= num

print(getKali)

mylist = [1, 2, 3, 4, 5]

getBagi = 1
for num in mylist:
    getBagi /= num

print(getBagi)

hm1 = [1, 2, 3, 4, 5]
hm2 = [1, 2, 3]

getSum1 = 0
for num in hm1:
    getSum1 += num

getSum2 = 0
for num in hm2:
    getSum2 += num

print(getSum1/getSum2)

hm1 = [1, 2, 3, 4, 5]
hm2 = [1, 2, 3]

getSum1 = 0
for num in hm1:
    getSum1 += num

getSum2 = 0
for num in hm2:
    getSum2 += num

print(getSum1-getSum2)